### ISSUE TITLE
Is this a demo?

### ISSUE THREAD

**Issue by DustScribe** [albertcht/laravel-swoole-demo#1]
Just Laravel source code?

**Comment by alpha2016** [comment]
With laravel-swoole package, nothing else, i don't understand what this mean.

**Comment by DustScribe** [comment]
@alpha2016 我已经成功用上了，你如果有问题，我可以提供一点帮助

**Comment by alpha2016** [comment]
@Mortence 请问你的应用场景是什么？处理队列的消息还是取代了nginx，为了提高效率？

**Comment by DustScribe** [comment]
@alpha2016 socket + 处理队列，你的使用场景呢

**Comment by alpha2016** [comment]
@Mortence 我暂时还没使用这个包，用 swoole 单独的文件做过处理队列，消息推送和聊天室，所以现在在看这个包，比单独文件去处理有多少优势的。

**Comment by DustScribe** [comment]
@alpha2016 用包的优势就是方便集成 ，相比直接使用 swoole ，这个包还有些功能没实现

**Comment by alpha2016** [comment]
@Mortence  对，我看文档也是，协程一类的功能暂时没集成的，原想着会有简单的应用场景demo，看来自己写比较靠谱

**Comment by DustScribe** [comment]
@alpha2016 是的

**Comment by alpha2016** [comment]
@Mortence 谢谢回复，不过作者这个项目有点水啊，什么实质内容也没有，就是一个安装了 laravel-swoole 的空包

**Comment by DustScribe** [comment]
@alpha2016 可能是作者觉得 demo 太简单了吧。我当时遇到的问题是在部署的时候，使用、配置其实都挺简单
